### ISSUE TITLE
Mail configuration profile

### ISSUE THREAD

**Issue by ehsandavari** [micromdm/nanomdm#125] opened 2024-05-07 12:19 UTC
how to install mail configuration profile on mac os user channel : https://developer.apple.com/documentation/devicemanagement/mail

**Comment by ehsandavari** [comment] 2024-05-07 13:19
i send this plist profile

<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\"><plist version=\"1.0\"><dict><key>PayloadContent</key><array><dict><key>EmailAccountDescription</key><string>asdasdas</string><key>EmailAccountName</key><string>ehsan</string><key>EmailAccountType</key><string>EmailTypePOP</string><key>EmailAddress</key><string>ehsandavari1379@gmail.com</string><key>IncomingMailServerAuthentication</key><string>EmailAuthNone</string><key>IncomingMailServerHostName</key><string>ads</string><key>IncomingMailServerPortNumber</key><integer>0</integer><key>IncomingMailServerUsername</key><string>ehsandavari1379@gmail.com</string><key>OutgoingMailServerAuthentication</key><string>EmailAuthNone</string><key>OutgoingMailServerHostName</key><string>asd</string><key>OutgoingMailServerPortNumber</key><integer>0</integer><key>OutgoingMailServerUseSSL</key><false/><key>OutgoingPasswordSameAsIncomingPassword</key><true/><key>allowMailDrop</key><false/><key>disableMailRecentsSyncing</key><false/><key>PayloadDisplayName</key><string>Mail</string><key>PayloadIdentifier</key><string>ed45c0ef-4c01-4268-b707-214944d21f77</string><key>PayloadOrganization</key><string>bba4b1a4-d399-46d3-9214-dcbcdba1249f</string><key>PayloadType</key><string>com.apple.mail.managed</string><key>PayloadUUID</key><string>3a354089-e199-4b9a-8a9f-b60dfc7b3fbb</string><key>PayloadVersion</key><integer>1</integer></dict></array><key>PayloadDescription</key><string/><key>PayloadDisplayName</key><string>ehsan</string><key>PayloadIdentifier</key><string>817a307d-3d92-4823-974e-51409f0eaa4a</string><key>PayloadOrganization</key><string>bba4b1a4-d399-46d3-9214-dcbcdba1249f</string><key>PayloadType</key><string>Configuration</string><key>PayloadUUID</key><string>1b8acff9-2e5f-497a-9223-ce9b92521802</string><key>PayloadVersion</key><integer>1</integer></dict></plist>


and MDM response is

<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>CommandUUID</key>\n\t<string>00355205-b193-417a-b249-6cf3f1178a7c</string>\n\t<key>ErrorChain</key>\n\t<array>\n\t\t<dict>\n\t\t\t<key>ErrorCode</key>\n\t\t\t<integer>-325</integer>\n\t\t\t<key>ErrorDomain</key>\n\t\t\t<string>ConfigProfilePluginDomain</string>\n\t\t\t<key>LocalizedDescription</key>\n\t\t\t<string>The profile contains one or more payloads that cannot be installed as a device profile</string>\n\t\t</dict>\n\t</array>\n\t<key>Status</key>\n\t<string>Error</string>\n\t<key>UDID</key>\n\t<string>95EA0E48-01D6-54EA-8EC1-A4A41B304B6A</string>\n</dict>\n</plist>

**Comment by jessepeterson** [comment] 2024-05-07 16:36
Duplicate of micromdm/micromdm#995.

**Closed by jessepeterson** 2024-05-07 16:36 UTC
